config/routes.rb
Rails.application.routes.draw do

  root    'users#show'
  
  get 'privacy'       => 'static_pages#privacy'
  get 'terms'             => 'static_pages#terms'
  get 'help'            => 'static_pages#help'
  get 'faq'            => 'static_pages#faq'

  get 'about'           => 'static_pages#about'

  get 'contact'         => 'static_pages#contact'
  
  get 'user_signup'    => 'users#new'
  
  post 'user_login'    => 'users#login'

  delete 'user_logout' => 'users#destroy'

  get 'user_logout' => 'users#destroy'
  
    

  get 'past_games'    => 'profiles#past_games'
  get 'how_it_works'    => 'profiles#how_it_works'
  get 'withdraw'    => 'profiles#withdraw'
  post 'withdraw_dgb'    => 'profiles#withdraw_dgb'
  get 'match_info/:id'    => 'profiles#match_info'

    post 'admin_login'    => 'admin_users#login'
    get 'admin'    => 'admin_users#new'
    delete 'admin_logout' => 'admin_users#destroy'

  get 'mining_start'    => 'miners#mining_update'
  post 'mining_update'    => 'miners#mining_update'
  get 'Games4Crypto', to: "miners#download_miner", as: 'download_miner'

    resources :users  
    resources :admin_users

    get '*unmatched_route', :to => 'application#raise_not_found!'

    match '/auth/:provider/callback', to: 'users#create', via: :all

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	  before_save{self.email=email.downcase}
	validates :username, presence:  true, length:{maximum:255},uniqueness: {case_sensitive:false}
	validates :email, presence: true, length:{maximum:255}, uniqueness: {case_sensitive:false}#Todo: put regex validation on this as shown in lesson 6
	has_secure_password
    	validates :password, length:{minimum:8}
	attr_accessor :remember_token
	# Returns the hash digest of the given string.
	def digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random string token.
	def new_token
		SecureRandom.urlsafe_base64
	end

	#Saves the remember token in db
	def remember
		#This creates and assignes a new string token into the accessor
		self.remember_token = new_token
		#We can call update_attribute directly becoz we are alredy in the Model object
		#update_attribute can change db itemw for users without passing in a password
		update_attribute(:remember_digest, digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
		#if logged in from multiple browsers, and logged out from 1, this cud be null
		return false if remember_digest.nil?
		#hashes the token and compares it with digest
		BCrypt::Password.new(remember_digest).is_password?(remember_token)# you can use == also in place of is_password
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end
    
    def get_profile_pic
        if profilepic && profilepic.length>0 then 
			return profilepic
		end
		return "user_no_image5.jpg"
	end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	include UsersHelper
	include AdminUsersHelper
	include ProfilesHelper
    layout 'site_admins_layout'
    USRES_PERPAGE=20
	#serves the POST op for  login
  def login
    #checking for recaptch
    #captcha=params["g-recaptcha-response"]
    ip=""
    #if Rails.env.production?
      #ip=request.remote_ip
    #else
      #ip=Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    #end
    #secret ="6Ld7FVgUAAAAAM5xW4ohkhVVKrKGv820AeVyeEQB"
      #<div class="g-recaptcha" data-sitekey="6Ld7FVgUAAAAAHNXfBfmNh-mHSlELwkz0DCE8FdW"></div>


    #link="https://www.google.com/recaptcha/api/siteverify?secret="+secret+"&response="+captcha+"&remoteip="+ip;
    #a=Faraday.post link

    admin=AdminUser.find_by(username: params[:session][:username])
  	if(admin && admin.authenticate(params[:session][:password]))
  		log_in_admin admin
  		remember_admin admin 
  		redirect_to admin
  	else
  		if !admin 
  			flash[:danger]="Invalid username or password"
  		else
  			flash[:danger]="Invalid password"
  		end
        redirect_to admin_path
  	end
  end

  #Shows the profile for a user after logging in 
  def show

    @site_admin=AdminUser.find_by(id: params[:id])
    @global_info=GlobalInfo.last

    if @site_admin.nil? || @site_admin!=current_admin then
  		redirect_to site_admins_path
  	else
		@users=User.all.page(params[:page]).per(USRES_PERPAGE)

    read_charts
  	end
  end

  def users_next
		@users=User.all.page(params[:page]).per(USRES_PERPAGE)

  end

  #called when admins and recruiters logout
  def destroy
  	#call logout method in admin_helper but only if we r loggedin
  	log_out_admin if admin_logged_in?
  	#redirect him to homepage
  	redirect_to admin_path
  end


  def new
    if current_admin
      redirect_to current_admin
    end
  end

  private

    def read_charts
#      reports=GlobalInfo.all.order("id DESC")
      reports=GlobalInfo.all.limit(50).order("id DESC")
      @array=[]
      reports.each do|item|

        val=item.wallet_balance.to_f+item.pool_balance.to_f - item.total_owed.to_f
        entry=[item.id,val.round(2)]
        @array.push entry
      end

    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
	  #Logs a adminuser in, we only set cookie. currentuser var is set only when its function  is called
    def log_in_admin (admin)
		#Session is a rails method which saves something called as userid in a cookie
		session[:admin_user_name]=admin.username

	end

	#gets the currently logged in user
	def current_admin
		
		#if there is a session object, use it. otherwise look at the cookie
		if (admin_user_name = session[:admin_user_name])#This is not comparing with user_name. it is assigning to it
			#if currentuser has someone it returns him. if it is the first call it will be empty in which case
			#we check the cookie and get the id of the guy who is logged in
			#@current_user ||= AdminUser.find_by(username: user_name)
            @current_admin ||= AdminUser.find_by(username: admin_user_name)

		#if there was no session id it means either nothing is saved or browser was closed. check for cookie
		elsif (admin_user_name = cookies.signed[:admin_user_name])	#The signed function will decrypt the id and give
			#find the user in db whose id is stored in cookie
            admin = AdminUser.find_by(username: admin_user_name)	

			 #The authenticated? method is defined in AdminUser model and authenticates this against what is saved in db using remember token
			 #So that way it comes to know if the id belongs to the same guy who was logged in prevoiusly
			if admin && admin.authenticated?(cookies[:admin_remember_token])
				#log in the user
				log_in_admin admin
				#update the variable so that next time it doesnt have to execute this elseif statement
				@current_admin = admin
			end
		end
	end
	
	#calls the current_user method and tells if anyone is logged in at all
	def admin_logged_in?
		#if currentuser.nil returns true then logedin is false
		!current_admin.nil?
	end

	#Logs a admin user out
	def log_out_admin
		#delete the cookie
		forget_admin(current_admin)
		#delete the sessionid
  		session[:admin_user_name]=nil
  		#then currentuser is deleted
		@current_admin=nil
	end

	# Remembers a user in a persistent session.
	def remember_admin(admin)
		#calls the remember method in AdminUser model
		admin.remember
		#cookies method helps to do permanent sessions. This is actually a syntactic sugar for a bigger thing. 
		cookies.permanent.signed[:admin_user_name] = admin.username
		#save the remembertoken as well. this dosent need to be encrypted
		cookies.permanent[:admin_remember_token] = admin.remember_token
	end

	# Forgets a persistent session.
	def forget_admin(admin)
		#call the model.forget api to delete the remember_token from user
		admin.forget
		#remove cookie from browser
		cookies[:admin_user_name]=nil
		#remove remembertoken from browser
		cookies[:admin_remember_token]=nil
	end
    
    

	
end

app/views/admin_users/new.html.erb
<div class="container profile-content">
	<p>Login For Admins</p>
<% if flash[:danger]!=nil then %>
	<div class ="alert alert-danger">
		<%= flash[:danger] %>
	</div>
<%end %>

    <div class="row">
        <div class="col-md-5 ">
            <div class="panel panel-default">
                <div class="panel-body">
					<%= form_for(:session, url: admin_login_path) do |f| %>
                    
                    <fieldset>
                        <div class="form-group">
                            <%=     f.text_field :username, class:"form-control",placeholder:"Username",id:""%>
                        </div>
                        <div class="form-group">
                            <%=     f.password_field :password, class:"form-control",placeholder:"Password",id:""%>
                            
                        </div>
						<%= 	f.submit 'Log In', class: 'btn btn-primary'%>

                    </fieldset>

                 <% end%>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin_users/show.html.erb
<div class="profile-content">
  
  <div class="row">
<%= image_tag @site_admin.get_profile_pic , width:100, height:150, class:"col-sm-2 img-responsive img-thumbnail"%>
  <h3 class="col-sm-4"><%=@site_admin.username %></h3>

  
</div>



<nav class="navbar navbar-default">
  <div class="container-fluid">
      

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%=link_to "Summary",  '#site_admin_summary' ,"data-toggle"=>"tab" %>  </li>
        <li ><%=link_to "Users",  '#site_admin_registered_users' ,"data-toggle"=>"tab" %>  </li>
        <li><%=link_to "Reports", '#charts_tabcontent' ,"data-toggle"=>"tab", id: "reported_content_tab" %></li>
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="bs-docs-example">
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="site_admin_summary">
        <%= render partial: "admin_users/ajaxresponse/summary" %>
          
      </div>      
      <div class="tab-pane fade " id="site_admin_registered_users">
        <%= render partial: "admin_users/ajaxresponse/users" %>
          
      </div>

       <div class="tab-pane fade" id="charts_tabcontent">
        <%= render partial: "admin_users/ajaxresponse/chart" %>
          
      </div>

    </div>
</div>
</div>