config/routes.rb
Rails.application.routes.draw do

  root    'users#show'
  
  get 'privacy'       => 'static_pages#privacy'
  get 'terms'             => 'static_pages#terms'
  get 'help'            => 'static_pages#help'
  get 'faq'            => 'static_pages#faq'

  get 'about'           => 'static_pages#about'

  get 'contact'         => 'static_pages#contact'
  
  get 'user_signup'    => 'users#new'
  
  post 'user_login'    => 'users#login'

  delete 'user_logout' => 'users#destroy'

  get 'user_logout' => 'users#destroy'
  
    

  get 'past_games'    => 'profiles#past_games'
  get 'how_it_works'    => 'profiles#how_it_works'
  get 'withdraw'    => 'profiles#withdraw'
  post 'withdraw_dgb'    => 'profiles#withdraw_dgb'
  get 'match_info/:id'    => 'profiles#match_info'

    post 'admin_login'    => 'admin_users#login'
    get 'admin'    => 'admin_users#new'
    delete 'admin_logout' => 'admin_users#destroy'

  get 'mining_start'    => 'miners#mining_update'
  post 'mining_update'    => 'miners#mining_update'
  get 'Games4Crypto', to: "miners#download_miner", as: 'download_miner'

    resources :users  
    resources :admin_users

    get '*unmatched_route', :to => 'application#raise_not_found!'

    match '/auth/:provider/callback', to: 'users#create', via: :all

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    POSTS_PERPAGE=20

	def past_games
		@level_1_tab="profile_tab"
		@level_2_tab="past_games"
    	@matches = current_user.matches.order('started_at DESC').page(params[:page]).per(POSTS_PERPAGE) if current_user

	end		

	def how_it_works
		@level_1_tab="profile_tab"
		@level_2_tab="how_it_works"

	end	
	#dig.conf file settings
#https://cryptocurrencytalk.com/topic/3137-digibyte-dgb-information/

#https://bitcoin.stackexchange.com/questions/58453/how-to-connect-to-bitcoind-from-ruby-rpc-client

	def withdraw
		@level_1_tab="profile_tab"
		@level_2_tab="withdraw"
		@withdrawals=Withdraw.where(user_id:current_user.id).order("id DESC");
	end

	def withdraw_dgb
		@level_1_tab="profile_tab"
		@level_2_tab="withdraw"


		error="Something went wrong!"
		withdraw=nil
		begin
			amount=params[:data][:amount].to_f
			address=params[:data][:address]
			if current_user 
				unless Withdraw.validate_address(address)
					error="Incorrect address!" 
					throw
				end		
				if  current_user.credits.to_f<amount
					error="Insufficient Balance!" 
					throw
				end
				unless amount > 10
					error="Amount should be greater than 10!" 
					throw
				end			
				amount_actual=amount- (0.01*amount)
				h = DigiByteRPC.new('http://game:Acidance69@127.0.0.1:12038')
				#p h.getbalance
				txid=""
				txid=h.sendtoaddress address, amount_actual
				if txid 
					balance=current_user.credits.to_f-amount
					current_user.credits=balance.to_s
					current_user.save
					withdraw=Withdraw.new(user_id:current_user.id, amount: amount_actual.to_s,address: address,txid: txid)
					withdraw.save

					#reduce from global object
					global_info=GlobalInfo.last
					total_paid=global_info.total_paid.to_f
					total_owed    =global_info.total_owed.to_f
					total_paid+=amount
					total_owed-=amount

					global_info.total_paid=total_paid.to_s
					global_info.total_owed=total_owed.to_s
					global_info.save
				end
				render :json => {error:false,message:"Withdrawal successful Txid: "+txid}

			end
		rescue Exception => ex
			render :json => {error:true,message:error}

		end

	end

	def match_info
		@level_1_tab="match_info"
		@level_2_tab="match_info"
	    @match = Match.includes(:players).find_by(id: params[:id])
    	@players = @match.players.order('slot ASC').group_by(&:radiant)
	end
end

class DigiByteRPC
  def initialize(service_url)
    @uri = URI.parse(service_url)
  end

  def method_missing(name, *args)
    post_body = { 'method' => name, 'params' => args, 'id' => 'jsonrpc' }.to_json
    resp = JSON.parse( http_post_request(post_body) )
    raise JSONRPCError, resp['error'] if resp['error']
    resp['result']
  end

  def http_post_request(post_body)
    http    = Net::HTTP.new(@uri.host, @uri.port)
    request = Net::HTTP::Post.new(@uri.request_uri)
    request.basic_auth @uri.user, @uri.password
    request.content_type = 'application/json'
    request.body = post_body
    http.request(request).body
  end

  class JSONRPCError < RuntimeError; end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    POSTS_PERPAGE=20
    POST_COMMENT_PERPAGE=10
        def get_updates 
            @updates={}
            page=params[:page]
            @articles=get_articles page, false

            userfailure=my_issues

            @new_groups=get_new_groups current_user, userfailure,page

            article_authors=@articles.map{|a| a.user_id}
            group_creators=@new_groups.map{|a| a.started_by}
            alluser_ids=article_authors+group_creators
            #all_users=User.where("id in (?)",alluser_ids)
            all_users=CacheUsers.from_ids(alluser_ids)
            @map_id_to_all_users={}
            all_users.map do |p|
                @map_id_to_all_users[p.id]=p
            end


            @total_count=@articles.count+@new_groups.count
        end

        def get_ndigitrandom n
            num=Random.new.rand((10**(n - 1))..(10**n))
            return num
        end



        def getchat_name anon,user
            id=get_ndigitrandom 10
            if anon
                @chat_user_id=""
                @chat_username=""
                @chat_user_id_anon="anon_"+id.to_s
                @chat_username_anon="Anonymous"
            else
                #return his actual info here
                @chat_user_id=user.id
                @chat_username=user.username
                @chat_user_id_anon="anon_"+id.to_s
                @chat_username_anon="Anonymous"

            end

        end 

        #The channels where those people push updates for their followers
        #If i need to get their feed, i need to subscriube to their channel
        def get_notification_channels
            #Subscribe to followers channel of all bussies who we have followed
            @following=Buddy.where(mentee_id: current_user.id, following:true).pluck(:mentor_id)
        end

        def get_room userid
            return "personal_"+userid.to_s
        end

        #This is the channel where all my sockets listen to
        #if someone wants to tell me something they shud put it here. this is like my mailbox
        def get_myroom
            return get_room current_user.id
        end
        #the rooms that he needs to register to
        def get_rooms
            isbuddy=get_current_buddystatus 
            @rooms_tojoin={}
            #structur is {"anonymous": true, groups:[], follow:[] , incoming=[]} 
            #Both follow and incoming gives upodates in which I hav to act on but the difference between follow and incoming is that
            #folow is a broadcast channel for others who send updates to people interested
            #incoming is directed to me and I do hav to act on it
            if isbuddy
                @rooms_tojoin["anonymous"]=true
            end

            #All follow channels
            get_notification_channels
            @rooms_tojoin["followers"]=[]

            @following && @following.each do |mentor_id|
                @rooms_tojoin["followers"].push( "followers_"+mentor_id.to_s)
            end

            #All incoming channels
            myroom=get_myroom
            @rooms_tojoin["incoming"]=[]

            @rooms_tojoin["incoming"].push( myroom)


            #All group channels
            #Todo

        end
        def summarise_updates_for_public_timeline
			@updates=MiningSession.where(user_id: current_user.id,state:1).order("id desc").page(params[:page]).per(POSTS_PERPAGE)

        	@running_session=MiningSession.where(user_id: current_user.id,state:0).limit(1)
        	if @running_session.count>=1
        		@running_session=@running_session[0]
        	else
        		@running_session=nil
        	end
		end

        def get_basic_profileinfo
            find_groups_joined(current_user) #inside therapyhelper
            get_rooms#rooms in nodejs channels that he needs to register to

            getchat_name false , current_user
        end        



        def get_basic_guestinfo
            @user=User.new#well show him signup page
            getchat_name true, nil
        end

        def get_basic_profileinfo_others user_id
            @person=CacheUsers.from_id user_id 
            #debugger
            @user_info=@person.user_info
        end

        def add_gunnerspace
            gunner=User.first
            (gunner && gunner.username=="gunnerspace") ?  gunner.id : nil
        end

    
        def summarise_updates_for_public_timeline2#Not Implemented Yet
		    #The above function shows everything in reverse chronological order
            #We need to find a way by which impoprtant tweets are showed first.
            #But important tweets alredy seen shud not be shown before less important ones not seen
            #So the logic is as follows
            #Let x be the post_id which he last saw.
            #And say everytime a post is being liked, or commented on we modify the post to save likecount and commentcount
            #So we take every post where id> x in order of modified timedesc (not created time), limit 30
            #So every post which was not seen will be placed in the order that it was most active
            #if we get less than 30 unseen posts, we need to extract some seen posts now.
            #Now get all posts where post_id<x order of modified timedesc limit 30 . So we will 
		end
            
            #To only get things posted by me
        def  summarise_updates_get_posts_foruser userid, failure_id="All"
            
            @mystory=MyStory.find_by(user_id: userid)
            @issues=UserFailure.where(user_id: userid)
            #@issueEventArray=[]
            #@issues && @issues.each do |issue|
                #myevents=Event.where(user_id: user.id,user_failure_id: issue.id)
                #issuename=Failure.failure_types[ issue.failure_id]
                #hash={issue: issuename, events: myevents}
                #@issueEventArray.push hash
            #end

            if failure_id=="All" || failure_id==nil then 
                @myevents=Event.where(user_id: userid)
            else
                @myevents=Event.where(user_id: userid,failure_id: failure_id)
            end

            @map_id_to_all_users={} unless @map_id_to_all_users
            @map_id_to_all_users[current_user.id]=current_user



            #debugger
        end

    
        def  getfollowings user
            idlist = getfollowings_id user
            @following=User.where("id in (?)",idlist)

        end 
        def getfollowings_id user
            @following_id=Following.where(follower_id:user.id,follow:true).pluck(:followee_id)#for folowing
            return @following_id

        end
        def  getfollowers user
            @followers_id=Following.where(followee_id: user.id,follow:true).pluck(:follower_id)#for folowing
            @followers=User.where("id in (?)",@followers_id)


        end
        def like_post_foruser post_id,liketype
            #check if alredy some action has happened
                        #debugger            

            @postlike=PostLike.find_by(user_id:current_user.id, post_id: post_id)
            if @postlike 
                if (@postlike.liketype==0 && liketype=="Like") || (@postlike.liketype==1 && liketype=="UnLike")
                    return;#we are alredy in the requestted state. Nothing to do here
                end
                if liketype=="Like"
                    @postlike.update_attribute("liketype" ,0)
                    Post.increment_counter(:likes, post_id ) 

                else
                    @postlike.update_attribute("liketype", 1)
                    Post.decrement_counter(:likes, post_id ) 

                    @newlike_type="Like"

                end
            else
                @postlike=PostLike.new(user_id:current_user.id, post_id: post_id,liketype:0)
                @postlike.save

                Post.increment_counter(:likes, post_id ) 
            end
        end

        def like_post_comment_foruser comment_id,liketype
            #check if alredy some action has happened

            @post_comment_like=PostCommentLike.find_by(user_id:current_user.id, post_comment_id: comment_id)
            if @post_comment_like 
                if (@post_comment_like.liketype==0 && liketype=="Like") || (@post_comment_like.liketype==1 && liketype=="UnLike")
                    return;#we are alredy in the requestted state. Nothing to do here
                end
                if liketype=="Like"
                    @post_comment_like.update_attribute("liketype" ,0)
                    PostComment.increment_counter(:likes, comment_id ) 

                else
                    @post_comment_like.update_attribute("liketype", 1)
                    PostComment.decrement_counter(:likes, comment_id ) 

                    @newlike_type="Like"

                end
            else
                @post_comment_like=PostCommentLike.new(user_id:current_user.id, post_comment_id: comment_id,liketype:0)
                @post_comment_like.save

                PostComment.increment_counter(:likes, comment_id ) 
            end
        end

        def upload_base_64_image value
            value.gsub!('data:image/jpeg;base64,', "")

            #File.open("/public/myimage.png", 'w') { |file| file.write(realdata) }
            #File.write("myimage.png", value)
            tempfile=Tempfile.new "myimage.png"
            File.open(tempfile.path, 'wb') do|f|
                f.write(Base64.decode64(value))
            end

            album=Album.find_by(user_id: current_user.id,  albumname:"Formations")
            if album.nil?
                album=Album.new(user_id: current_user.id, albumname: "Formations", caption: "This is a default album containing pictures from your Formations created")
                album.save
            end

            hash={tempfile: tempfile, filename: "formation",type: "image/jpeg" , head: ""}
            pic=ActionDispatch::Http::UploadedFile.new hash

app/views/profiles/ajaxresponse/_details_table.html.erb
<h3 class="<%= team %>">Team <%= team.titleize %></h3>

<table class="table table-hover table-striped info-table">
  <tr>
    <th>Player ID</th>
    <th>Hero</th>
    <th>Level</th>
    <th>Items</th>
    <th>Kills</th>
    <th>Deaths</th>
    <th>Assists</th>
    <th><abbr title="Last hits">LH</abbr></th>
    <th><abbr title="Denies">DN</abbr></th>
    <th>Gold (spent)</th>
    <th><abbr title="Gold per minute">GPM</abbr></th>
    <th><abbr title="Experience per minute">XPM</abbr></th>
    <th><abbr title="Hero damage">HD</abbr></th>
    <th><abbr title="Tower damage">TD</abbr></th>
    <th><abbr title="Hero healing">HH</abbr></th>
  </tr>
  <% players && players.each do |player| %>
    <tr>
      <td>
        <% if player.abandoned_or_not_connected? %>
          <abbr class="text-muted" title="<%= player.status.to_s.titleize %>"><%= player.uid %></abbr>
        <% else %>
          <%= player.uid %>
        <% end %>
      </td>
      <td><%= render 'profiles/ajaxresponse/player_hero', hero: player.hero %></td>
      <td><%= player.level %></td>
      <td><%= render 'profiles/ajaxresponse/items', items: player.items %></td>
      <td><%= player.kills %></td>
      <td><%= player.deaths %></td>
      <td><%= player.assists %></td>
      <td><%= player.last_hits %></td>
      <td><%= player.denies %></td>
      <td><%= player.gold %> (<%= player.gold_spent %>)</td>
      <td><%= player.gpm %></td>
      <td><%= player.xpm %></td>
      <td><%= player.hero_damage %></td>
      <td><%= player.tower_damage %></td>
      <td><%= player.hero_healing %></td>
    </tr>
    <% if player.additional_units.any? %>
      <% player.additional_units && player.additional_units.each do |unit| %>
        <tr class="text-muted small">
          <td></td>
          <td><%= unit[:name] %></td>
          <td></td>
          <td><%= render 'profiles/ajaxresponse/items', items: unit[:items] %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

<h4 class="<%= team %>">Builds</h4>

<table class="table table-hover table-striped info-table">
  <tr>
    <th>Hero</th>
    <% (1..20).each do |level| %>
      <th><%= level %></th>
    <% end %>
  </tr>
  <% @players[true].each do |player| %>
    <tr>
      <td><%= render 'profiles/ajaxresponse/player_hero', hero: player.hero %></td>
      <%player.ability_upgrades &&  player.ability_upgrades.each do |ability| %>
        <td class="text-center">
          <%= image_tag ability[:image], alt: ability[:name], title: ability[:name] %><br/>
          <small class="text-muted"><%= ability[:time] %></small>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<h4 class="<%= team %>">Remaining buildings</h4>

<h5>Towers</h5>

<ul>
  <% @match.towers_status[team.to_sym].each do |b| %>
    <li><%= b.to_s.titleize %></li>
  <% end %>
</ul>

<h5>Barracks</h5>

<ul>
  <% @match.barracks_status[team.to_sym].each do |b| %>
    <li><%= b.to_s.titleize %></li>
  <% end %>
</ul>

app/views/profiles/ajaxresponse/_get_started.html.erb
<!-- https://bootsnipp.com/snippets/featured/services-section-using-bootstrap-4-->
	<section id="what-we-do">
		<div class="container-fluid">
			<h2 class="section-title mb-2 h1">Get Started</h2>
			<p class="text-center text-muted h5">Looks like you have not started using the website. Follow the steps to get started and earn money through cryptocurrency</p>
			<div class="row mt-5">
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-1">
							<h3 class="card-title">Download Miner</h3>
							<p class="card-text">Download the windows miner by clicking the green button on the left.</p>
							<a href="/how_it_works" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-2">
							<h3 class="card-title">Login into Miner</h3>
							<p class="card-text">Enter the userid shown on the left to login into the miner.</p>
							<a href="/how_it_works" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
							
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-3">
							<h3 class="card-title">Start Miner</h3>
							<p class="card-text">Click on the Start button on the miner which will perform a series of operations. Once it says running, you are good to go!</p>
							<a href="/how_it_works" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
							
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-4">
							              <h3 class="card-title">Enable API access in Dota2</h3>
              <p class="card-text">You would need to enable API access in your Dota2 console, so that Steam APIs can access them. Click below video to learn more.</p>

            <div class=" disc_video">
                    <a href="https://www.youtube.com/watch?v=rXh40-tKjL4" >
                        <img class="img-responsive" src="https://img.youtube.com/vi/rXh40-tKjL4/0.jpg" alt="IMAGE ALT TEXT">
                    </a>
            </div>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-5">
							<h3 class="card-title">Play Dota2 Online</h3>
							<p class="card-text">Open Dota2 and play online. You get digibyte credits for gaming. Wins pay more than losses</p>
							<a href="/how_it_works" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
							
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-4">
					<div class="card">
						<div class="card-block block-6">
							<h3 class="card-title">Antivirus Warnings</h3>
							<p class="card-text">You might get antivirus warnings while running the miner. Please add AV exclusion for miners </p>
							<a href="/how_it_works" title="Read more" class="read-more" >Read more<i class="fa fa-angle-double-right ml-2"></i></a>
						
						</div>
					</div>
				</div>
			</div>
		</div>	
	</section>
<script>
$(document).ready(function(){
          $('.disc_video a').magnificPopup({
          type: 'iframe'

        });   

});

    
</script>

app/views/profiles/ajaxresponse/_how_it_works.html.erb
<!-- https://bootsnipp.com/snippets/featured/services-section-using-bootstrap-4-->
  <section id="what-we-do">
    <div class="container-fluid">
      <h2 class="section-title mb-2 h1">How it works</h2>
      <p class="text-center text-muted h5">Follow the below instructions to start off with using this website.</p>
      <div class="row mt-5">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-1">
              <h3 class="card-title">Download Miner</h3>
              <p class="card-text">Download the windows miner by clicking the green button on the left.</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-2">
              <h3 class="card-title">Login into Miner</h3>
              <p class="card-text">Enter the userid shown on the left to login into the miner.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-3">
              <h3 class="card-title">Start Miner</h3>
              <p class="card-text">Click on the Start button on the miner which will perform a series of operations. It will initially download a set of miners and start running them. The operation will succeed only if you have a graphics card powerfull enough for mining. Once it says running, you are good to go!</p>
            </div>
          </div> 
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-4">
              <h3 class="card-title">Enable API access in Dota2</h3>
              <p class="card-text">You would need to enable API access in your Dota2 console, so that Steam APIs can access them. Click below video to learn more.</p>

            <div class=" disc_video">
                    <a href="https://www.youtube.com/watch?v=rXh40-tKjL4" >
                        <img class="img-responsive" src="https://img.youtube.com/vi/rXh40-tKjL4/0.jpg" alt="IMAGE ALT TEXT">
                    </a>
            </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-5">
              <h3 class="card-title">Play Dota2 Online</h3>
              <p class="card-text">Open Dota2 and play online. You get digibyte credits for gaming. Wins pay more than losses</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <div class="card">
            <div class="card-block block-6">
              <h3 class="card-title">Antivirus Warnings</h3>
              <p class="card-text">You might get antivirus warnings while running the miner. Please add AV exclusion for miners </p>
            </div>
          </div>
        </div>
      </div>
    </div>  
  </section>
<script>
$(document).ready(function(){
          $('.disc_video a').magnificPopup({
          type: 'iframe'

        });   

});

    
</script>

app/views/profiles/ajaxresponse/_items.html.erb
<% items && items.each do |item| %>
  <%= image_tag item[:image], alt: item[:name], title: item[:name] %>
<% end %>

app/views/profiles/ajaxresponse/_match_details.html.erb
<%won=false%>
<%status="lost"%>
<% if current_user.won?(match) %>
  <%won=true%>
  <%status="won"%>
  <p class="label label-success game_status">Match won</p>
<% else %>
  <p class="label label-danger game_status">Match lost</p>
<% end %>
<%hero =current_user.played_for_in(match) %>



<%if hero %>
    <div class="match_hero">
      <%= image_tag hero[:image], alt: hero[:name], title: hero[:name]  %>
    </div>    
    <p>Played as <%=hero[:name] %> on <%=match.started_at.strftime("%B %-d  %Y,   %l:%M %p")%> and <%=status%></p>

<% else%>
  <p>Played match on <%=match.started_at.strftime("%B %-d  %Y,   %l:%M %p")%> and <%=status%></p>

<%end%>
 <%= link_to"Visit Match ", "/match_info/#{match.id}"  ,class:""%>

app/views/profiles/ajaxresponse/_posts.html.erb
<div id="social_networking_post_only_area">
    <%= render partial: "profiles/ajaxresponse/post_snippet" %>

</div>
<%= paginate @updates, :params => {:controller => 'profiles', :action => 'show_my_profile_home'},:locals => { rem: true }%>

app/views/profiles/ajaxresponse/_show_my_profile.html.erb
<% unless current_user  %>
<%= render partial: "users/landing_page" %>

<%else%>




<!--https://bootsnipp.com/snippets/featured/user-profile-sidebar-->
<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <%= image_tag current_user.avatar_url ,   class:" img-responsive"%>
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        <%=current_user.username%>
                    </div>
                    <div class="profile-usertitle-job">
                        UserId: <%=current_user.miningid%>
                    </div>
                    <div class="profile-earnings">
                        Earnings: <%=current_user.credits.to_f.round(2)%> DGB
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <div class="profile-userbuttons">
                     <%= link_to"Download Miner", download_miner_path ,class:"btn btn-success btn-sm"%>
                     <%= link_to"Withdraw", withdraw_path ,class:"btn btn-danger btn-sm"%>


                </div>
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
        <%= render partial: "profiles/ajaxresponse/show_my_profile_sidebar" %>

                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9" >
            <div class="profile-content" id="social_networking_posts">
               <%if @level_2_tab=="past_games"%>
                    <%= render partial: "profiles/ajaxresponse/show_past_games" %>             
                <%elsif @level_2_tab=="withdraw"%>
                    <%= render partial: "profiles/ajaxresponse/withdraw" %>               
                 <%elsif @level_2_tab=="how_it_works"%>
                    <%= render partial: "profiles/ajaxresponse/how_it_works" %>
                <%else%>
                    <%= render partial: "profiles/ajaxresponse/posts" %>

                <%end%>   
            </div>
        </div>
    </div>
</div>
    


<%end%>

  

app/views/profiles/ajaxresponse/_withdraw.html.erb
<div id="withdraw_area">
      <h2 class="withdraw-title mb-2 h1">Withdraw DigiBytes</h2>

<div class="container">
    <div class="row">
        <div class="col-md-5 ">
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= form_for(:data, url: withdraw_dgb_path,remote:true, html: {id:'withdrawalform'}) do |f| %>
                    
                    <fieldset>
                        <div class="form-group">
                            <%=     f.text_field :address, class:"form-control",placeholder:"Withdrawal Address",id:""%>

                        </div>
                        <div class="form-group">
                            <%=     f.text_field :amount, class:"form-control",placeholder:"Amount",id:"new_advices_failurelist"%>
                            
                        </div>

                    <%=     f.submit 'Withdraw', class: 'btn btn-primary   '%>
                    </fieldset>

                 <% end%>

                </div>
            </div>
        </div>
    </div>
</div>


</div>
<div class="withdraw_history">
	<h4>Withdrawal History</h4>
	<%if @withdrawals && @withdrawals.count>0%>

		<%@withdrawals.each do |withdraw|%>

        
            
                <div class="[ panel panel-default ] panel-google-plus">
                    <div class="dropdown">
                        <span class="dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="[ glyphicon glyphicon-chevron-down ]"></span>
                        </span>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>

                        </ul>
                    </div>

                    <div class="panel-heading">

                    </div>
                    <div class="panel-body social_net_post_content" id="social_net_post_content">
						<p>Txid: <a href="https://digiexplorer.info/tx/<%=withdraw.txid%>" target="_blank"><%=withdraw.txid%></a></p>
						<p>Amount: <%=withdraw.amount%></p>
						<p>Address: <a href="https://digiexplorer.info/address/<%=withdraw.address%>" target="_blank"><%=withdraw.address%></a></p>
                        <p>Time :  <%= withdraw.created_at.strftime("%B %-d,  %Y, %H:%M")  %> </p>
                        
                    </div>
                </div>
            

        	
		<%end%>
	<%else%>
		<p>Nothing to show</p>
	<%end%>
</div>