config/routes.rb
Rails.application.routes.draw do

  root    'users#show'
  
  get 'privacy'       => 'static_pages#privacy'
  get 'terms'             => 'static_pages#terms'
  get 'help'            => 'static_pages#help'
  get 'faq'            => 'static_pages#faq'

  get 'about'           => 'static_pages#about'

  get 'contact'         => 'static_pages#contact'
  
  get 'user_signup'    => 'users#new'
  
  post 'user_login'    => 'users#login'

  delete 'user_logout' => 'users#destroy'

  get 'user_logout' => 'users#destroy'
  
    

  get 'past_games'    => 'profiles#past_games'
  get 'how_it_works'    => 'profiles#how_it_works'
  get 'withdraw'    => 'profiles#withdraw'
  post 'withdraw_dgb'    => 'profiles#withdraw_dgb'
  get 'match_info/:id'    => 'profiles#match_info'

    post 'admin_login'    => 'admin_users#login'
    get 'admin'    => 'admin_users#new'
    delete 'admin_logout' => 'admin_users#destroy'

  get 'mining_start'    => 'miners#mining_update'
  post 'mining_update'    => 'miners#mining_update'
  get 'Games4Crypto', to: "miners#download_miner", as: 'download_miner'

    resources :users  
    resources :admin_users

    get '*unmatched_route', :to => 'application#raise_not_found!'

    match '/auth/:provider/callback', to: 'users#create', via: :all

end

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container">
			<div class="navbar-header">
		  
		
		<%= link_to "Games4Crypto", current_admin, id: "logo" %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        	</div>
			<div class="collapse navbar-collapse" id="collapse">
				<nav>
					<ul class="nav navbar-nav navbar-right">

						<% if admin_logged_in? %>
							<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							My Account <b class="caret"></b>
							</a>
								<ul class="dropdown-menu">
                                    <li><%= link_to "Edit Profile", current_admin %></li>
									<li><%= link_to "Settings", '#' %></li>
                                    <li><%= link_to "Help", help_path %></li>
									<li class="divider"></li>
									<li>
                                        <%= link_to "Log out", admin_logout_path, method: "delete" %>
									</li>
								</ul>
							</li>	
						<%else %>
							<li><%= link_to "Log in", '#' %></li>
						<%end%>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_common_snippets.erb
 
<div class=" hide" id="waitgif">
    <div class="container">
        <%= image_tag "wait.gif",  class:"icon"%>

    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="container">

<!-- margin-left: -347px; -->
             

          
	<nav>
	
		<ul>
		
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "FAQ", faq_path %></li>
		    <li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Terms of Service", terms_path %></li>
			<li><%= link_to "Privacy Policy", privacy_path %></li> 
			<li><%= link_to image_tag("twitter_G4C.png", border: 0), "https://twitter.com/Games4Crypto", target: :_blank %> </li>
		</ul>
		
	</nav>
	<p class="text-muted">@Copyright Games4Crypto.com
	
	</div>

</footer>

	

app/views/layouts/_header.html.erb
<%articles_tab_class=""%>
<%articles_tabcontent_class=""%>
<%profile_tab_class=""%>
<%profile_tabcontent_class=""%>
<%lendahand_tab_class=""%>
<%lendahand_tabcontent_class=""%>
      

<%if @level_1_tab=="articles_tab" || @level_1_tab=="show_article"  %>
      <%articles_tab_class="active"%>
    <%articles_tabcontent_class="in active"%>
<%elsif @level_1_tab=="profile_tab" || @level_1_tab=="others_profile" || @level_1_tab=="welcome_tab" %>
      <%profile_tab_class="active"%>
    <%profile_tabcontent_class="in active"%>
<%elsif @level_1_tab=="group_admin"  %>
    <%lendahand_tab_class="active"%>
    <%lendahand_tabcontent_class="in active"%>
<%end%>
<%i=4%>
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
      <%= link_to image_tag("Games4CryptoLogoText.png") , root_path, id: "logo" %>
          
          </div>
      <div class="collapse navbar-collapse" id="collapse">
        <nav>
          <ul class="nav navbar-nav navbar-right">

                <% if logged_in? %>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        
                          <li><%= link_to "Help", help_path %></li>
                          <li class="divider"></li>
                         
                          <li><%= link_to "Log out", user_logout_path, method: "delete" %></li>
                        </ul>
                    </li> 
                <%else %>
          
                   <li class=""><%=link_to "Login with Steam", "/auth/steam"  %></li>
          
                  <%end%>
          </ul>
        </nav>
      </div>
    </div>
  </header>


<div class="bs-docs-example">
    <div id="myTabContent" class="tab-content">

      <div class="tab-pane fade <%=profile_tabcontent_class%>" id="my_profile_tabcontent">
        <%if @level_1_tab=="profile_tab"  %>
            <%= render partial: "profiles/ajaxresponse/show_my_profile" %>
        <%elsif @level_1_tab=="others_profile"  %>
          <%= render partial: "profiles/ajaxresponse/show_user_profile" %>       
        <%elsif @level_1_tab=="welcome_tab"  %>
          <%= render partial: "profiles/ajaxresponse/welcome_message" %> 
        <%end%>
      </div>  
        
        <div class="tab-pane fade <%=lendahand_tabcontent_class%>" id="lendahand_tabcontent">
        <%if @level_1_tab=="group_admin"  %>
            <%= render  :partial => 'therapy/admin/lendahand' %>

        <%end%>

      </div>
      <div class="tab-pane fade <%=articles_tabcontent_class%>" id="articles_tabcontent">
        <%if @level_1_tab=="articles_tab" %>
            <%= render partial: "articles/ajaxresponse/articles" %>
         <%elsif @level_1_tab=="show_article"  %>
          <%= render partial: "articles/ajaxresponse/show_article" %> 
        <%end%>
      </div>

    </div>
</div>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games4Crypto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'games4crypto.ico' %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<%= render 'layouts/shim'%>
</head>
<body>

<%= render 'layouts/header'%>

		<%= yield %>
    <%= render 'layouts/common_snippets' %>

		<%= render 'layouts/footer' %>
</body>

</html>

app/views/layouts/site_admins_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games4Crypto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
  <%= favicon_link_tag 'games4crypto.ico' %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim'%>
</head>
<body>

    <%= render 'layouts/admin_header'%>

	<div class="container">
		<%= yield %>
    <%= render 'layouts/common_snippets' %>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>